---
title: "Structural driver of plant community and  it's associated phylloshere microbiota"
author: "Mathis Gheno"
format: html
editor: visual
bibliography: references.bib
zotero: false
---

# Overview of communities structure under high environmental pressure.

## Plants

@Buzhdygan2020Biodiversity Multitrophic complementary, the higher biodiversity at any trophic level benefits the entire system regarding energy flow/use

@Odum1985Trends In a stressful environment, r-strategy tends to out-compete K-strategy organisms. The number of trophic levels or length of food chains tends to decrease, mostly because big organisms are less tolerant to stress. Sometimes stress reduces biodiversity, but it is not always the case. If the ecosystem climax is low abundance, maybe perturbation could increase abundance.

@Tilman2001Diversity More diversity = more biomass productivity and carbon accumulation with the effect of niche complementary

#### Landscape

@SilveiradosSantos2022Landscape Test collinearity bewteen landscape with **VIF**. Effect positive effect of compositional heterogeneity and negatively patches with irregular shape (**colinéaire land pour la varaible "shape"** : patron irrégulier = penten, hetrogeneité des paysage ...) on plant richness $\rightarrow$ process of dispersion and pollination (*maybe if seed bank is more impact than the last two : less effect of landscape?*)

## Bacteria

@Zhang2016Stochastic Bactria community are strongly structured by salinity gradiant. Shared OTU between high and medium is important. More phylogenetic diversity in medium and high salinity pressure (especially in medium). Rare OTU increases with salinity, but diversity is similar between high and low .

-   *Bacteroidetes*, *Protobacteria* (except *betaprotobacteria = low*), *Gemmatimonadetes* and *Firmicutes (*Gram-positive cell) have a high-salt environment

-   *Nitriliruptorales* in medium salt environment

-   *Acidobacteria*, *Chloroflexi*, *Cyanobacteria* and *Micrococcales* in low salt environnement

The impact (not signif. only a tendency) of pH is weaker than salinity impact on the structure of B. communities when spacial is considered.

## Virus

@Roux2016Analysis Viral community structured given salt gradient in halophilic environments. Genetic similarity along the saline gradient and geographical localization (especially for high salinity). In highly halophilic environment, virus communities are genetically closer to each other than communities that are close geographically speaking. Co-evolution between host and virus?

@Andreote2017Microbial Community structure along the pH, calcium and altitude gradients. *Siphoviridae* family correlate negatively with other virus

@Wicaksono2023Viral More gene for complex polysaccharide breakdown in the area dried out for over 10 years. More lysogenic in early stage / high salinity. High correlation between viral and bacterial community structure (and prokaryotic also)

# Unclassifiable

(Une definition un peu random, mais qui souleve des idées interessantes) La notion de stabilité d'un écosystème est elle-même fort complexe ; elle s'apprécie par des paramètres, variés, relatifs à la constance et à la durée d'un état d'équilibre, à l'inertie ou résistance aux perturbations, à l'amplitude des perturbations supportables, à la vitesse de retour, à l'équilibre, etc.
