---
title: "multi var analysis"
output: html_document
date: "2024-01-26"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Packages
```{r}
library(FactoMineR)
library(factoextra)
library(tidyverse)
library(corrplot)
library(ade4)
library(vegan)
library(RColorBrewer)
main_theme = theme_bw()+
  theme(line = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        axis.ticks =  element_line(colour = "black"),
        axis.text.x = element_text(colour = "black", size=10),
        axis.text.y = element_text(colour = "black", size=10),
        legend.title = element_text(colour = "black", size=20),
        legend.title.align=0.5,
        legend.text = element_text(colour = "black", size=15),
        axis.title=element_text(size=10),
        strip.background = element_rect(fill="cornsilk"))
```

## Data 

```{r}
read.table("data/Metadata_Grid_CAM.txt", header = T)%>%
  rename(M_cu= "Milieux_cultives",
         Z_hu= "Zones_humides",
         M_nat = "Forets_et_milieux_naturels_terrestres",
         Z_eau = "Zones_en_eau",
         Abun = "plant_abundance_grid",
         d_oxy = "Profondeur") -> metadata_grid

out_plant = read.table("data/otu_plant_grid_CAM.txt")

out_plant_df = out_plant[,-1]
#attr(out_plant_matrix, "dimnames")[[1]] = out_plant$Grid_code


```

## First projection : co-interie (only quantitative variable for now)

### Env
```{r}
metadata_grid %>%
  select(where(is.numeric), -c(buffer_size, Num, grid, biomass_sd))%>%
  
  scale()-> metadata_grid_quanti
cor(metadata_grid_quanti)%>%
  corrplot( method = "square")

######### PCA analysis of env variables
pca_env <- dudi.pca(metadata_grid_quanti,scannf=F,nf=2)
s.corcircle(pca_env$co)
s.traject(pca_env$li)
s.label(pca_env$li,add.plot=T)

fviz_pca_ind(pca_env, col.ind = "cos2",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)
fviz_pca_var(pca_env, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)
fviz_pca_biplot(pca_env, repel = TRUE,col.var = "#2E9FDF",col.ind = "#696969")

# Valeurs propres
eig.val_env <- get_eigenvalue(pca_env)
eig.val_env
barplot(eig.val_env$variance.percent, names.arg = rownames(eig.val_env), xlab = "axes", ylab = "axes percentage inertie")
# Results for variables
res.var_env <- get_pca_var(pca_env)
res.var_env$coord          # Coordonates
1/nrow(res.var_env$contrib)*100
str(res.var_env$contrib/colSums(res.var_env$contrib)*100)
as.data.frame(res.var_env$contrib/colSums(res.var_env$contrib)*100)%>%
  arrange(desc(Dim.1))# Contributions to axes
res.var_env$cos2           # Quality of the plot 
# Results for individuals
res.ind_env <- get_pca_ind(pca_env)
res.ind_env$coord          # Coordonates
res.ind_env$contrib        # Contributions to axes
res.ind_env$cos2    
```

### Cover
```{r}
out_plant_df %>%
  decostand(method = "hellinger") -> otu_plant_scale
par(mfrow = c(2,1))
barplot(colSums(otu_plant_scale),type = "text")
barplot(colSums(out_plant_df),type = "text")
######### PCA analysis of env variables
pca_cover <- PCA(otu_plant_scale, plot =F)
plot(pca_cover)
s.corcircle(pca_cover$li)
s.traject(pca_cover$li)
s.label(pca_cover$li,add.plot=T)

fviz_pca_ind(pca_cover, col.ind = "cos2",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)
fviz_pca_ind(pca_cover, col.ind = "contrib",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07", repel = TRUE))
fviz_pca_var(pca_cover, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), geom = c( "point"), repel = TRUE)

# clustering
CAH_cover = HCPC(pca_cover, metric = "euclidean", method = "ward", nb.clust =3)


fviz_pca_ind(pca_cover,col.var = "orange2", repel = TRUE, habillage = CAH_cover$data.clust$clust,
                addEllipses=TRUE, ellipse.level=0.95)+
  scale_color_brewer(palette="Set1") +
  scale_fill_brewer(palette="Set1")+
  main_theme
ggplot(metadata_grid)+
  geom_point(aes(X,Y, col = CAH_cover$data.clust$clust))
```

### co-inerte
```{r}
coinetie_env_cover = coinertia(dudiX = pca_env, dudiY = pca_cover, nf = 2, scannf = FALSE)
randtest(coinetie_env_cover,nrepet=10000)
plot(randtest(coinetie_env_cover),main="Monte-Carlo test")

coinetie_env_cover$eig/sum(coinetie_env_cover$eig)*100

#QUESTION: #what are the values ? is it high ? do you know why?

#study inertia and absolute contributions:
iner=inertia.dudi(coinetie_env_cover,col.inertia=T,row.inertia=T)
iner
abscoiV=iner$col.abs
abscoiV
str(abscoiV)
#take a threshold, for instance, 1*100/number of variables:

selectV=rbind(abscoiV[abscoiV[,1] > (100/nrow(abscoiV)),],
              abscoiV[abscoiV[,2] > (100/nrow(abscoiV)),])
selectV

abscoiE=iner$row.abs
abscoiE
#select species contributing to more than 0.5 % (adapt the percentage to the dataset):
str(abscoiE[abscoiE[,2]>0.5,])
selectE=rbind(abscoiE[abscoiE[,1]>0.5,], abscoiE[abscoiE[,2]>0.5,])


#plot the coinertia:
plot(coinetie_env_cover)#global view
```

## Second projection : co-interie (remove some correlated varaibles)

### Env
```{r}
cor(metadata_grid_quanti)%>%
  corrplot( method = "square")
str(metadata_grid_quanti)
data.frame(metadata_grid_quanti)%>%
  select(-c(X,Y, MO, C, N,Ca,Na, clay, SiltF,Mg, Cl, Cond)) ->clean_metadata_grid_quanti
cor(clean_metadata_grid_quanti)%>%
  corrplot( method = "number")
######### PCA analysis of env variables
pca_env2 <-PCA(clean_metadata_grid_quanti, graph =F)
str(pca_env)
pca_env$var$contrib
fviz_pca_var(pca_env2, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)
fviz_pca_ind(pca_env2, col.ind = "cos2",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

# clustering
CAH_env = HCPC(pca_env2, metric = "euclidean", method = "ward", nb.clust =3)

fviz_pca_biplot(pca_env2,col.var = "orange2", repel = TRUE, habillage = CAH_env$data.clust$clust,
                addEllipses=TRUE, ellipse.level=0.95)+
  scale_color_brewer(palette="Set1") +
  scale_fill_brewer(palette="Set1")+
  main_theme

ggplot(metadata_grid)+
  geom_point(aes(X,Y, col = CAH_env$data.clust$clust))+
  scale_color_brewer(palette="Set1") 
# Valeurs propres
eig.val_env <- get_eigenvalue(pca_env2)
eig.val_env
# Results for variables
res.var_env <- get_pca_var(pca_env2)
res.var_env$coord          # Coordonates
1/nrow(res.var_env$contrib)*100
str(res.var_env$contrib/colSums(res.var_env$contrib)*100)
as.data.frame(res.var_env$contrib/colSums(res.var_env$contrib)*100)%>%
  arrange(desc(Dim.1))# Contributions to axes
res.var_env$cos2           # Quality of the plot 
# Results for individuals
res.ind_env <- get_pca_ind(pca_env2)
res.ind_env$coord          # Coordonates
res.ind_env$contrib        # Contributions to axes
res.ind_env$cos2    
```

### co-inerte
```{r}
pca_env_co = dudi.pca(clean_metadata_grid_quanti,scannf=F,nf=2)
pca_cover_co <- dudi.pca(otu_plant_scale,scannf=F,nf=2)

coinetie_env_cover = coinertia(dudiX = pca_env_co, dudiY = pca_cover_co, nf = 2, scannf = FALSE)
randtest(coinetie_env_cover,nrepet=1000)
plot(randtest(coinetie_env_cover),main="Monte-Carlo test")

coinetie_env_cover$eig/sum(coinetie_env_cover$eig)*100

#QUESTION: #what are the values ? is it high ? do you know why?

#study inertia and absolute contributions:
iner=inertia.dudi(coinetie_env_cover,col.inertia=T,row.inertia=T)
iner
abscoiV=iner$col.abs
abscoiV
str(abscoiV)
#take a threshold, for instance, 1*100/number of variables:

selectV=rbind(abscoiV[abscoiV[,1] > (100/nrow(abscoiV)),],
              abscoiV[abscoiV[,2] > (100/nrow(abscoiV)),])
selectV

abscoiE=iner$row.abs
abscoiE
#select species contributing to more than 0.5 % (adapt the percentage to the dataset):
str(abscoiE[abscoiE[,2]>0.5,])
selectE=rbind(abscoiE[abscoiE[,1]>0.5,], abscoiE[abscoiE[,2]>0.5,])


#plot the coinertia:
plot(coinetie_env_cover)#global view
s.corcircle(coinetie_env_cover$c1,box = FALSE, grid = TRUE,  possub = "bottomleft",cgrid = 0, fullcircle = TRUE, add.plot = FALSE)
```