---
title: "Untitled"
output: html_document
date: "2024-02-20"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(vegan)
library(ade4)
library(car)
library(ggpubr)
library(ggrepel)
library(RColorBrewer)
library(sf)
# objet pour mettre en forme les graphiques ggplot
main_theme = theme_bw()+
  theme(line = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        axis.ticks =  element_line(colour = "black"),
        axis.text.x = element_text(colour = "black", size=22),
        axis.text.y = element_text(colour = "black", size=22),
        legend.title = element_text(colour = "black", size=20),
        legend.title.align=0.5,
        legend.text = element_text(colour = "black", size=18),
        axis.title=element_text(size=28))
```

```{r}
read.table("data/data_clean/Metadata_grid_CAM.txt", header = T) -> metadata_grid
  
metadata_quadra = read.table("data/data_clean/Metadata_quadra_CAM.txt")
OUT_plant = read.table("data/data_clean/OTU_plant_CAM.txt")

read.table("data/data_clean/abund_plant_grid.txt", header = T, row.names = "Grid_code")-> abund_plant_grid 

read.table("data/data_clean/TAX_plant_CAM.txt")-> tax_plant


```

```{r}
colnames(metadata_grid)
metadata_grid%>%
  dplyr::select(pHwater, lime_tot, MO, Phos, K, Mg, Ca, Na, N, C, 
         CN, clay, SiltF, SiltC, SandF, SandC, Cl, Res, Cond,
         dep_oxy_num, Pature, Fauche, natural_landscape, cultivated, artificial, non_emitting,wetland)%>%
  mutate(across(c(Pature,Fauche), as.factor),
    across(where(is.numeric), ~decostand(., method = "standardize")))-> metadata_grid_standard

abund_plant_grid %>%
  select(where( function(x) sum(x) >1))%>%
  decostand(method = "hellinger")-> abund_plant_stantdard # select species represented at only one site. 10 is the lower abundance possible
str(abund_plant_stantdard)
```

```{r}
rda_full = rda(abund_plant_stantdard ~ .  ,metadata_grid_standard)
rda_full$call

p_var_full = summary(rda_full)
### Avec colinéarité:

# Partitioning of variance:
#               Inertia Proportion
# Total          0.4917     1.0000
# Conditioned    0.0924     0.1879 => Partie expliquée par la dépendance spatiale
# Constrained    0.2305     0.4689 => Partie expliquée par les variables env.
# Unconstrained  0.1687     0.3432

RsquareAdj(rda_full)$adj.r.squared
RsquareAdj(rda_full)$r.squared   # => Notre modèle explique à ~47% l'assemblage des communautés (correspond à la partie "Constrained" de la rda)
round(vif.cca(rda_full),2)
```

```{r}

plot(rda_full)
```

```{r}
#-c(natural, MO, C, Cond, SiltF,clay,SandC,Cl,Mg)
metadata_grid_standard%>%
  select(-c(MO, N,Cond, SiltF, SandC, Mg, Na, artificial, cultivated, clay)) -> metadata_grid_selected
rda_selected = rda(abund_plant_stantdard ~ .  ,metadata_grid_selected)
round(vif.cca(rda_selected),2)

```

```{r}
plot(rda_selected)
summary(rda_selected)
```

```{r}
rda_ordistep <- ordiR2step(rda(abund_plant_stantdard ~ 1, metadata_grid_selected),
                      scope = formula(rda_selected),
                      direction = "both",
                      R2scope = F,
                      pstep = 10000,
                      trace = FALSE)
p_var_full3 = summary(rda_ordistep)
str(p_var_full3)
p_var_full3  
```

```{r}
rda_ordistep$tot.chi
anova.cca(rda_ordistep, permutations = 10000)

anova_rda_ordistep = anova.cca(rda_ordistep, permutations = 10000, by ="term")

# conversion en pourcentage pour faciliter l'interprétation
str(anova_rda_ordistep)
anova_rda_ordistep$Variance = (anova_rda_ordistep$Variance/ rda_ordistep$tot.chi)*100
anova_rda_ordistep

```

```{r}
RsquareAdj(rda_ordistep)$r.square
```

```{r, fig.show='hide'}

pl <- ordiplot(rda_ordistep,scaling = 1)
perc <- round(100*(summary(rda_ordistep)$cont$importance[2, 1:3]), 2)
str(perc)

```

```{r}
# Type 1 scaling
par(mfrow = c(1,1))

##### Sites
env_var = as.data.frame(pl$biplot*attr(pl$biplot,"arrow.mul"))
env_var$type = rownames(env_var)

env_var_discret = as.data.frame(pl$centroids[c(2,4),])
env_var_discret$type = rownames(env_var_discret)

sites = as.data.frame(pl$sites)
sites$type = rownames(sites)

species = as.data.frame(pl$species)
ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.30,"cm"), ends="first", type = "closed"), linewidth = 1)+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 3.5)+
  geom_text_repel(data = sites, aes(x=RDA1,y = RDA2, label = type), cex = 3,max.overlaps = 40,col = "steelblue")+
  geom_point(data = species, aes(x=RDA1,y = RDA2), col = "darkolivegreen4")+
  
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"))+
  main_theme
```

```{r}
cluster2_sp = hcut(species, hc_metric = "euclidean", hc_method = "ward.D2", k =2)
cluster3_sp = hcut(species, hc_metric = "euclidean", hc_method = "ward.D2", k =3)
cluster4_sp = hcut(species, hc_metric = "euclidean", hc_method = "ward.D2", k =4)
cluster5_sp = hcut(species, hc_metric = "euclidean", hc_method = "ward.D2", k =5)
fviz_silhouette(cluster2_sp)
fviz_silhouette(cluster3_sp)
fviz_silhouette(cluster4_sp)
fviz_silhouette(cluster5_sp)



cluster2_sites = hcut(sites[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =2)
cluster3_sites = hcut(sites[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =3)
cluster4_sites = hcut(sites[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =4)
cluster5_sites = hcut(sites[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =5)
fviz_silhouette(cluster2_sites)
fviz_silhouette(cluster3_sites)
fviz_silhouette(cluster4_sites)
fviz_silhouette(cluster5_sites)

cluster3_site_df = data.frame(cluster3_sites$data, clust = as.factor(cluster3_sites$cluster))
```

```{r}
cluster_sp_df = data.frame(cluster5_sp$data, clust = as.factor(cluster5_sp$cluster))

cluster_sp_df$Plant_species = rownames(cluster_sp_df)

cluster_sp_df%>%
  full_join(tax_plant, by = join_by("Plant_species"))-> cluster_sp_df
```

```{r}
env_var$type = c("Res","Non em.", "Ca","Lime","K", "P", "Cl", "SandF", "Wetland", "Nat. land", "pH")
env_var_discret$type = c("Mow", "Pasture")
ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = clust), size = 2,stroke=1.2, shape =4)+
  geom_label_repel(data = cluster_sp_df,aes(x=RDA1,y = RDA2, col = clust, label = Plant_species), cex = 2,alpha = 0.80)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Cluster species", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())
```

```{r}

g1 = ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = Salinity_tolerance), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Salinity tolerance", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())

g2 = ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = life_style), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Life style", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())

#ggarrange(g1, g2)

g1
g2
```

```{r}
ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = GRIME), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Grime", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())

ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = Plant_photosynthetic_pathway), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Photo path", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())
```
```{r}

 ggplot()+
  geom_segment(data = env_var,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df, aes(x=RDA1,y = RDA2, col = Plant_order), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster3_site_df, aes(x=RDA1,y = RDA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret,aes(x=RDA1,y = RDA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret,aes(x=RDA1,y = RDA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), col = "Plant order", shape = "Cluster sites")+
  main_theme+
   theme(line = element_line())
unique(cluster_sp_df$Plant_order)
```

##CCA

```{r}
cca_full = cca(abund_plant_stantdard ~ .  ,metadata_grid_standard)
cca_full$call

p_var_full = summary(cca_full)
### Avec colinéarité:

# Partitioning of variance:
#               Inertia Proportion
# Total          0.4917     1.0000
# Conditioned    0.0924     0.1879 => Partie expliquée par la dépendance spatiale
# Constrained    0.2305     0.4689 => Partie expliquée par les variables env.
# Unconstrained  0.1687     0.3432

RsquareAdj(cca_full)$adj.r.squared
RsquareAdj(cca_full)$r.squared   # => Notre modèle explique à ~47% l'assemblage des communautés (correspond à la partie "Constrained" de la cca)
round(vif.cca(cca_full),2)
```

```{r}

plot(cca_full)
```

```{r}
#-c(natural, MO, C, Cond, SiltF,clay,SandC,Cl,Mg)
metadata_grid_standard%>%
  select(-c(N, Cond, SiltC, SandC, SiltF, Mg, Na, clay, artificial, cultivated, MO)) -> metadata_grid_selected
cca_selected = cca(abund_plant_stantdard ~ .  ,metadata_grid_selected)
round(vif.cca(cca_selected),2)

```

```{r}
plot(cca_selected)
summary(cca_selected)
```

```{r}
cca_ordistep <- ordiR2step(cca(abund_plant_stantdard ~ 1, metadata_grid_selected),
                      scope = formula(cca_selected),
                      direction = "both",
                      R2scope = F,
                      pstep = 10000,
                      trace = FALSE)
p_var_full3 = summary(cca_ordistep)
str(p_var_full3)
p_var_full3  
```

```{r}
cca_ordistep$tot.chi
anova.cca(cca_ordistep, permutations = 10000)

anova_cca_ordistep = anova.cca(cca_ordistep, permutations = 10000, by ="term")

# conversion en pourcentage pour faciliter l'interprétation
str(anova_cca_ordistep)
anova_cca_ordistep$ChiSquare = (anova_cca_ordistep$ChiSquare/ cca_ordistep$tot.chi)*100


```

```{r}
RsquareAdj(cca_ordistep)$r.square
```

```{r, fig.show='hide'}

pl_CCA <- ordiplot(cca_ordistep,scaling = 1)
perc <- round(100*(summary(cca_ordistep)$cont$importance[2, 1:3]), 2)
str(perc)

```

```{r}
# Type 1 scaling

par(mfrow = c(1,1))

##### Sites
env_var_CCA = as.data.frame(pl_CCA$biplot*attr(pl_CCA$biplot,"arrow.mul"))
env_var_CCA$type = rownames(env_var_CCA )

env_var_discret_CCA = as.data.frame(pl_CCA$centroids[c(2,4),])
env_var_discret_CCA$type = rownames(env_var_discret_CCA)

site_CAA = as.data.frame(pl_CCA$site)
site_CAA$type = rownames(site_CAA)

species_CAA = as.data.frame(pl_CCA$species)
ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.30,"cm"), ends="first", type = "closed"), linewidth = 1)+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 3.5)+
  geom_text_repel(data = site_CAA, aes(x=CCA1,y = CCA2, label = type), cex = 3,max.overlaps = 40,col = "steelblue")+
  geom_point(data = species_CAA, aes(x=CCA1,y = CCA2), col = "darkolivegreen4")+
  
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"))+
  main_theme
```

```{r}
cluster2_sp_CCA = hcut(species_CAA, hc_metric = "euclidean", hc_method = "ward.D2", k =2)
cluster3_sp_CCA = hcut(species_CAA, hc_metric = "euclidean", hc_method = "ward.D2", k =3)
cluster4_sp_CCA = hcut(species_CAA, hc_metric = "euclidean", hc_method = "ward.D2", k =4)
cluster5_sp_CCA = hcut(species_CAA, hc_metric = "euclidean", hc_method = "ward.D2", k =5)
fviz_silhouette(cluster2_sp_CCA)
fviz_silhouette(cluster3_sp_CCA)
fviz_silhouette(cluster4_sp_CCA)
fviz_silhouette(cluster5_sp_CCA)



cluster2_site_CAA = hcut(site_CAA[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =2)
cluster3_site_CAA = hcut(site_CAA[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =3)
cluster4_site_CAA = hcut(site_CAA[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =4)
cluster5_site_CAA = hcut(site_CAA[,1:2], hc_metric = "euclidean", hc_method = "ward.D2", k =5)
fviz_silhouette(cluster2_site_CAA)
fviz_silhouette(cluster3_site_CAA)
fviz_silhouette(cluster4_site_CAA)
fviz_silhouette(cluster5_site_CAA)

cluster_site_df_CAA = data.frame(cluster3_site_CAA$data, clust = as.factor(cluster3_site_CAA$cluster))
```

```{r}
cluster_sp_df_CCA = data.frame(cluster3_sp_CCA$data, clust = as.factor(cluster3_sp_CCA$cluster))

cluster_sp_df_CCA$Plant_species = rownames(cluster_sp_df_CCA)

cluster_sp_df_CCA%>%
  full_join(tax_plant, by = join_by("Plant_species"))-> cluster_sp_df_CCA
```

```{r}
env_var_CCA $type = c("Res","Non em.", "Cl","SanF","Wetlands", "Ca", "Lime", "K", "Nat. lands")
env_var_discret_CCA$type = c("Mow", "Pasture")
ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = clust), size = 2, stroke=1.2, shape =4)+
  geom_label_repel(data = cluster_sp_df_CCA,aes(x=CCA1,y = CCA2, col = clust, label = Plant_species), cex = 2,alpha = 0.80)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"), col = "Cluster species", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())
```

```{r}

g1 = ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = Salinity_tolerance), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"), col = "Salinity tolerance", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())

g2 = ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = life_style), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"), col = "Life style", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())

#ggarrange(g1, g2)

g1
g2
```

```{r}
ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  #geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2),col = "gray", size = 2,stroke=1.2, shape =4, alpha = 0.4,na.rm = T)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = GRIME), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"), col = "Grime", shape = "Cluster sites")+
  scale_color_manual(values =c("#4885ff","#8103ff", "#c8ffb2","#ffd727", "#ffc484" ,"#ff4242"))+
  main_theme+
   theme(line = element_line())

ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = Plant_photosynthetic_pathway), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CCA2 (", perc[2], "%)"), col = "Photo path", shape = "Cluster sites")+
  scale_color_brewer(palette ="Set1")+
  main_theme+
   theme(line = element_line())
```

```{r}

 ggplot()+
  geom_segment(data = env_var_CCA ,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1.5, col = "gray3")+
  geom_label_repel(data = env_var_CCA ,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
   geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2),col = "gray", size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_sp_df_CCA, aes(x=CCA1,y = CCA2, col = Plant_order), size = 2,stroke=1.2, shape =4)+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2.4, col = "black")+
  geom_point(data = cluster_site_df_CAA, aes(x=CCA1,y = CCA2, shape = clust), cex = 2, col = "darkgray")+
  geom_segment(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2, xend =0, yend = 0), arrow = arrow(length=unit(0.20,"cm"), ends="first", type = "open"), size = 1, col = "gray3")+
  geom_label_repel(data = env_var_discret_CCA,aes(x=CCA1,y = CCA2,label = type),  cex = 5, alpha = 0.75)+
  labs(x = paste0("CCA1 (", perc[1], "%)"), y = paste0("CAA2 (", perc[2], "%)"), col = "Plant order", shape = "Cluster sites")+
  main_theme+
   theme(line = element_line())
unique(cluster_sp_df_CCA$Plant_order)
```

```{r}

st_read("data/shapefiles/sql_statement_d551600.shp") -> map_contour

metadata_grid%>%
  dplyr::select(X,Y)%>%
  st_as_sf(coords = c("X", "Y"), crs = st_crs(map_contour))%>%
  st_buffer(6000)%>%
  st_union()%>%
  st_cast(to = "POLYGON") ->limit_map

map_contour = st_crop(x = map_contour, y =limit_map)



map_contour%>%
  ggplot()+
  geom_sf(col = "gray" )+
  geom_point(data = metadata_grid,aes(X,Y, col = cluster_site_df_CAA$clust),  cex = 2.5)+
  geom_text_repel(data = metadata_grid,aes(X,Y, col = cluster_site_df_CAA$clust, label = 1:42),  cex = 3.5)+
  scale_fill_brewer(palette = "Pastel2")+
  scale_color_brewer(palette = "Set1")+
  labs(colour = "Grid cluster", fill ="Cover type")+
  main_theme

map_contour%>%
  ggplot()+
  geom_sf(col = "gray" )+
  geom_point(data = metadata_grid,aes(X,Y, col = cluster3_site_df$clust),  cex = 2.5)+
  geom_text_repel(data = metadata_grid,aes(X,Y, col = cluster_site_df_CAA$clust, label = 1:42),  cex = 3.5)+
  scale_fill_brewer(palette = "Pastel2")+
  scale_color_brewer(palette = "Set1")+
  labs(colour = "Grid cluster", fill ="Cover type")+
  main_theme
```


```{r}
library(adespatial)
library(spdep)

data(mafragh)
mxy <- as.matrix(data.frame(X = metadata_grid$X, Y = metadata_grid$Y))

nbgab <- graph2nb(gabrielneigh(mxy), sym = TRUE)
ade4::s.label(
  boxes = F,
  as.data.frame(mxy),
  neig = nb2neig(nbgab),
  xlim=c(min(mxy[,1]), max(mxy[,1])),
  ylim=c(min(mxy[,2])-0.01, max(mxy[,2])+0.01)
)

distgab <- nbdists(nbgab, mxy)

fdist <- lapply(distgab, function(x) 1 - x/max(dist(mxy)))

listwgab <- nb2listw(nbgab, glist = distgab)
mem.gab.positive <- orthobasis.listw(listwgab, wt = rep(1, length(listwgab$neighbours)),
                            MEM.autocor = "positive",
                            store.listw = T)
mem.gab.negative <- orthobasis.listw(listwgab, wt = rep(1, length(listwgab$neighbours)),
                            MEM.autocor = "negative",
                            store.listw = T)

scalo <- scalogram(OUT_plant_grid_binary_clean[,11], mem.gab.positive)

#s.value(as.data.frame(mxy), mem.gab.positive[,1:6])
plot(mem.gab.positive, as.data.frame(mxy), pSp.cex = 3)

#plot(scalo)
barplot(mem.gab.positive$MEM3)

# mspa.hell <- mspa(pca.hell, listwgab, scannf = FALSE, nf = 2)
# 
# g.mspa <- scatter(mspa.hell, posieig = "topright", plot = FALSE)
# g.mem <- s.value(mafragh$xy, mem.gab.positive[, c(1, 2, 6, 3)], Sp = mafragh$Spatial.contour, ppoints.cex = 0.4, plegend.drawKey = FALSE, plot = FALSE)
# g.abund <- s.value(mafragh$xy, mafragh$flo[, c(31,54,25)], Sp = mafragh$Spatial.contour, symbol = "circle", col = c("black", "palegreen4"), plegend.drawKey = FALSE, ppoint.cex = 0.4, plot = FALSE)
# 
# p1 <- list(c(0.01, 0.44), c(0.64, 0.15), c(0.35, 0.01), c(0.15, 0.78))
# for (i in 1:4)
# g.mspa <- insert(g.mem[[i]], g.mspa, posi = p1[[i]], plot = FALSE)
# 
# p2 <- list(c(0.27, 0.54), c(0.35, 0.35), c(0.75, 0.31))
# for (i in 1:3)
# g.mspa <- insert(g.abund[[i]], g.mspa, posi = p2[[i]], plot = FALSE)
# 
# g.mspa
```

